version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-agg
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql  

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: news_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: news_db
    restart: always
    environment:
      MYSQL_DATABASE: news_agg
      MYSQL_USER: news_agg
      MYSQL_PASSWORD: news_agg
      MYSQL_ROOT_PASSWORD: root_news_agg
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge